### ISSUE TITLE
Servers.pm not found

### ISSUE THREAD

**Issue by ERRMoody** [josephryan/Hernandez_Ryan_2019_RecodingSim#1]
Hi, I was wondering if you could help with this error? The servers.pm module is definitely in 01-MODULES, so I'm a bit confused why it's giving this issue:

```
user@IT072283:~/Hernandez_Ryan_2019_RecodingSim/02-COMPOSITIONAL_HETEROGENEITY/02-HETEROGENEOUS_DATA$ perl chunkify_comphet_trees.pl 
Can't locate Servers.pm in @INC (you may need to install the Servers module) (@INC contains: ~/user/Hernandez_Ryan_2019_RecodingSim/01-MODULES/ /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at chunkify_comphet_trees.pl line 10.
```
Thanks,
Ed

**Comment by josephryan** [comment]
Hi Ed,
I updated the chunkify script. 
In version 0.02, line 9 read:  `use lib qw(/Hernandez_Ryan_2019_RecodingSim/01-MODULES/);`
In version 0.03 it reads: `use lib qw(../../01-MODULES/);`
If you run the script from the `02-HETEROGENEOUS_DATA` directory within the downloaded repo it should find it.
If you you want to run it from anywhere, adjust this line to be the full path to the 01-MODULES directory.
Thanks for letting us know, and sorry for the confusion.
Joe
